package br.com.wsilva.tasko.tasko.core.domain.model.os

data class ServicoTipo(
    var idServicoTipo: Int,
    var descricaoServicoTipo: String,
    var idSubgrupo: Int = 0,
    var indicadorAtualizacaoComercial: Int = 0,
    var indicadorPavimento: Int = 0,
    var indicadorServicoTerceirizado: Int = 0,
    var valorServico: Float = 0f,
    var tempoMedioExecucao: Float = 0f,
    var idDebitoTipo: Int = 0,
    var idCreditoTipo: Int = 0,
    var idPrioridade: Int = 0,
    var idPerfilTipoServico: Int = 0,
    var idTipoServicoReferencia: Int = 0,
    var indicadorVistoria: Int = 0,
    var indicadorFiscalizacaoInfracao: Int = 0,
    var valorRemuneracao: Int = 0,
    var percentualRemuneracao: Int = 0,
    var prazoexEcucaoServico: Int = 0,
    var indicadorTipoRemuneracao: Int = 0,
    var indicadorInformarDeslocamento: Int = 0,
    var indicadorInformarHorarioExecucao: Int = 0,
    var indicadorInformarCausaVazamento: Int = 0,
    var indicadorInformarRedeRamal: Int = 0,
    var indicadorInformarRedeRamalEsgoto: Int = 0,
    var indicadorInformarMaterial: Int = 0,
    var indicadorInfomarVala: Int = 0,
    var indicadorOrdemSeletiva: Int = 0,
    var indicadorServicoCritico: Int = 0,
    var indicadorAtividadeUnica: Int = 0,
)    